# Generated by Django 4.2.27 on 2025-12-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available_hours', models.DecimalField(decimal_places=2, help_text='Tillgängliga timmar per vecka.', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(choices=[(1, 'Lätt'), (2, 'Måttlig'), (3, 'Svår'), (4, 'Mycket Svår')], default=2, help_text='Svårighetsgrad (1-4).')),
                ('estimated_time', models.DecimalField(decimal_places=2, help_text='Beräknad tid att slutföra (timmar).', max_digits=4)),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='management.resource')),
            ],
        ),
    ]
