# Generated by Django 4.2.27 on 2025-12-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='role',
            field=models.CharField(default='Medlem', max_length=100),
        ),
    ]
